environment:
  nodejs_version: '6'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install --ignore-scripts

test_script:
  - node --version
  - npm --version
  - npm test

build_script: npm run build
